### ISSUE TITLE
Keymapping for completion

### ISSUE THREAD

**Issue by elkrien** [optimizacija/neovim-config#3]
Hi,

Can You help mi with setting navigation through popup menu with autocompletion? I know that in .vimrc format the command should be:

```
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
```

But how can I do it with lua format? Sorry, maybe this is noob question but I'm still learning and coudn't find documentation. 

BTW - I love Your config, did some modifications and it works flawlessly on my computer ;)

**Comment by optimizacija** [comment]
Hi @elkrien, sorry for the late reply. 
I kind of  fell out of practice, but I believe that you're looking for something like this.
 
```nvim
vim.api.nvim_set_keymap('i', '<Tab>', 'pumvisible() ? "\<C-n>" : "\<Tab>"', {expr = true, noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<S-Tab>', 'pumvisible() ? "\<C-p>" : "\<S-Tab>"', {expr = true, noremap = true, silent = true})
```

I am glad to hear that you're enjoying this config! But I'm sad to let you know that some of the plugins are not working anymore. Since the 0.6 update, a lot of the plugins that I use had their setups rewritten.

**Comment by optimizacija** [comment]
fixed the majority of issues, should work again.
